services:

  kafka-1:
    image: confluentinc/cp-kafka:7.7.0
    container_name: kafka-1
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - kafka_data_1:/var/lib/kafka/data
    networks:
      - nlhtung-net

  # kafka-2:
  #   image: confluentinc/cp-kafka:7.7.0
  #   container_name: kafka-2
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - "9093:9092"
  #     - "29093:29092"
  #   environment:
  #     KAFKA_BROKER_ID: 2
  #     KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://localhost:29092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
  #     KAFKA_LISTENER_PORT: 9092
  #     KAFKA_LISTENER_HOST: kafka-2
  #     KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  #   healthcheck:
  #     test: ["CMD-SHELL", "cub kafka-ready -b kafka-2:9092 1 1"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   volumes:
  #     - kafka_data_2:/var/lib/kafka/data
  #   networks:
  #     - nlhtung-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka-1
      #- kafka-2
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9092 #,kafka-2:9092
    networks:
      - nlhtung-net

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - nlhtung-net

  minio-init:
    image: minio/mc
    container_name: minio-init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        sleep 10;
        mc alias set myminio http://minio:9000 minioadmin minioadmin;
        mc mb myminio/bronze myminio/silver myminio/gold;
        mc policy set public myminio/raw myminio/cleaned" 
    networks:
      - nlhtung-net

  spark-master:
    build:
      context: .
      dockerfile: spark/Dockerfile
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    ports:
      - "8080:8080" 
      - "7077:7077"
      - "4040:4040"
    volumes:
      - ./spark/config/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - ./hive-metastore/hive-site.xml:/opt/bitnami/spark/conf/hive-site.xml
      - ./spark/jobs:/opt/spark-apps
    networks:
      - nlhtung-net

  spark-worker-1:
    build:
      context: .
      dockerfile: spark/Dockerfile
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
    ports:
      - "8081:8081"
    depends_on:
      - spark-master
    volumes:
      - ./spark/jobs:/opt/spark-apps
      - ./hive-metastore/hive-site.xml:/opt/bitnami/spark/conf/hive-site.xml
    networks:
      - nlhtung-net
  
  spark-worker-2:
    build:
      context: .
      dockerfile: spark/Dockerfile
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
    ports:
      - "8082:8081"
    depends_on:
      - spark-master
    volumes:
      - ./spark/jobs:/opt/spark-apps
      - ./hive-metastore/hive-site.xml:/opt/bitnami/spark/conf/hive-site.xml
    networks:
      - nlhtung-net

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 10s
      retries: 5
    networks:
      - nlhtung-net

  hive-metastore:
    image: apache/hive:4.0.0
    container_name: hive-metastore
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      HIVE_METASTORE_DB_TYPE: postgres
      HIVE_METASTORE_DB_HOST: postgres
      HIVE_METASTORE_DB_PORT: 5432
      HIVE_METASTORE_DB_NAME: hive
      HIVE_METASTORE_DB_USER: hive
      HIVE_METASTORE_DB_PASSWORD: hivepw
      SERVICE_NAME: metastore
      HADOOP_CLASSPATH: /opt/hive/lib/hadoop-aws-3.3.4.jar:/opt/hive/lib/aws-java-sdk-bundle-1.12.262.jar
    ports:
      - "9083:9083"
    volumes:
      - ./hive-metastore/hive-site.xml:/opt/hive/conf/hive-site.xml
      - ./jars/postgresql-42.7.7.jar:/opt/hive/lib/postgresql-42.7.7.jar
      - ./jars/hadoop-aws-3.3.4.jar:/opt/hive/lib/hadoop-aws-3.3.4.jar
      - ./jars/aws-java-sdk-bundle-1.12.262.jar:/opt/hive/lib/aws-java-sdk-bundle-1.12.262.jar
    entrypoint: >
      bash -c "
      echo '⏳ Initializing Hive schema in PostgreSQL...';
      /opt/hive/bin/schematool -dbType postgres -userName hive -passWord hivepw -url jdbc:postgresql://postgres:5432/hive -initSchema || echo '⚠️ Schema already initialized';
      echo '✅ Hive schema ready, starting metastore service...';
      /opt/hive/bin/hive --service metastore
      "
    networks:
      - nlhtung-net

  airflow-redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - nlhtung-net

  airflow-init:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    container_name: airflow-init
    depends_on:
      postgres:
        condition: service_healthy
      airflow-redis:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://airflow-redis:6379/0
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__FERNET_KEY=z_lL_eTlP5BTuFAYKS8t4sqVfh97hySVN3PW4NCcwy4=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./spark/jobs:/opt/spark-apps
      - ./spark/config:/opt/spark-config
    entrypoint: /bin/bash
    command: >
      -c "
      airflow db init && 
      airflow users create --username admin --password admin --firstname admin --lastname user --role Admin --email admin@example.com &&
      airflow connections add 'spark_master' --conn-type 'spark' --conn-host 'spark://spark-master' --conn-port '7077'"
    networks:
      - nlhtung-net

  airflow-webserver:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    container_name: airflow-webserver
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      airflow-redis:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://airflow-redis:6379/0
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__FERNET_KEY=z_lL_eTlP5BTuFAYKS8t4sqVfh97hySVN3PW4NCcwy4=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=your-consistent-secret-key
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./spark/jobs:/opt/spark-apps
      - ./spark/config:/opt/spark-config
    ports:
      - "8686:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /opt/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - nlhtung-net

  airflow-scheduler:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    container_name: airflow-scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      airflow-redis:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://airflow-redis:6379/0
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__FERNET_KEY=z_lL_eTlP5BTuFAYKS8t4sqVfh97hySVN3PW4NCcwy4=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=your-consistent-secret-key
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./spark/jobs:/opt/spark-apps
      - ./spark/config:/opt/spark-config
    command: scheduler
    healthcheck:
      test: ["CMD-SHELL", "airflow jobs check --job-type SchedulerJob --local"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - nlhtung-net

  airflow-worker:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    container_name: airflow-worker
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      airflow-redis:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://airflow-redis:6379/0
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__FERNET_KEY=z_lL_eTlP5BTuFAYKS8t4sqVfh97hySVN3PW4NCcwy4=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=your-consistent-secret-key
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./spark/jobs:/opt/spark-apps
      - ./spark/config:/opt/spark-config
    command: celery worker
    healthcheck:
      test: ["CMD-SHELL", "celery --app airflow.executors.celery_executor.app inspect ping -d celery@$HOSTNAME"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - nlhtung-net

  trino-coordinator:
    image: trinodb/trino:414
    container_name: trino-coordinator
    ports:
      - "8088:8080"
    volumes:
      - ./trino:/etc/trino/catalog
    command: >
      bash -c "/usr/lib/trino/bin/run-trino --server --coordinator"
    networks:
      - nlhtung-net

  trino-worker:
    image: trinodb/trino:414
    container_name: trino-worker
    depends_on:
      - trino-coordinator
    volumes:
      - ./trino:/etc/trino/catalog
    command: >
      bash -c "/usr/lib/trino/bin/run-trino --server --worker"
    networks:
      - nlhtung-net

  superset:
    build:
      context: .
      dockerfile: superset/Dockerfile
    container_name: superset
    depends_on:
      postgres:
        condition: service_healthy
      trino-coordinator:
        condition: service_started
    environment:
      - SUPERSET_SECRET_KEY=supersetsecretkey
      - SUPERSET_ENV=production
      - DATABASE_DB=superset
      - DATABASE_HOST=postgres
      - DATABASE_PASSWORD=superset
      - DATABASE_USER=superset
      - DATABASE_PORT=5432
      - DATABASE_DIALECT=postgresql
      - SUPERSET_LOAD_EXAMPLES=no
    ports:
      - "8089:8088"
    volumes:
      - superset_data:/app/superset_home
      - ./superset/superset_config.py:/app/superset_config/superset_config.py
    command: >
      bash -c "
      superset db upgrade &&
      superset fab create-admin --username admin --firstname Admin --lastname User --email admin@superset.com --password admin &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debugger"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8088/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - nlhtung-net

volumes:
  kafka_data_1:
  minio_data:
  postgres_data:
  airflow_redis_data:
  superset_data:

networks:
  nlhtung-net:
    driver: bridge